torrents:
    rootPath: "/tmp/torrents"
    frequency: 5 seconds

    number_one:
        url: "http://www.ezrss.it/search/index.php?simple&show_name=Game+of+Thrones&mode=rss"
        path: "number_one_dir"
        frequency: 3 hours

    number_two:
        url: "http://www.ezrss.it/search/index.php?show_name=Walking+Dead&date=&quality=&release_group=&mode=rss"
        path: "number_two_dir"

    number_three:
        url: "http://www.ezrss.it/search/index.php?show_name=simpsons&date=&quality=&release_group=&mode=rss"


